global:
  scrape_interval: 1m
  evaluation_interval: 1m   
rule_files:
  - "prometheus.rules.yml"
  - "alerts.yml"
scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 1m
    static_configs:
    - targets: ["localhost:9090"]

  - job_name: "node"
    static_configs:
    - targets: ["195.206.171.28:9100"]
